type MenuEng = {
  id: number;
  name: string;
  category: string;
  price: string;
  description: string;
  availability: boolean;
  allergens: string[];
};

export const menuEng: MenuEng[] = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    category: "Main Course",
    price: "12_99",
    description: "Classic Italian pasta with rich bolognese sauce",
    availability: true,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 2,
    name: "Caesar Salad",
    category: "Appetizer",
    price: "6_99",
    description: "Fresh romaine lettuce with Caesar dressing and croutons",
    availability: true,
    allergens: ["dairy", "egg"],
  },
  {
    id: 3,
    name: "Chocolate Cake",
    category: "Dessert",
    price: "5_99",
    description: "Rich and moist chocolate cake",
    availability: true,
    allergens: ["gluten", "dairy", "nuts"],
  },
  {
    id: 4,
    name: "Margherita Pizza",
    category: "Main Course",
    price: "10_99",
    description: "Classic pizza with tomato sauce, mozzarella, and basil",
    availability: true,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 5,
    name: "Grilled Salmon",
    category: "Main Course",
    price: "14_99",
    description: "Perfectly grilled salmon served with lemon butter sauce",
    availability: true,
    allergens: ["fish"],
  },
  {
    id: 6,
    name: "Vegan Burger",
    category: "Main Course",
    price: "11_99",
    description: "Plant-based patty with lettuce, tomato, and vegan mayo",
    availability: true,
    allergens: ["gluten"],
  },
  {
    id: 7,
    name: "Mango Smoothie",
    category: "Beverage",
    price: "4_99",
    description:
      "Refreshing mango smoothie made with fresh mangoes and almond milk",
    availability: true,
    allergens: ["nuts"],
  },
  {
    id: 8,
    name: "Garlic Bread",
    category: "Appetizer",
    price: "3_99",
    description: "Toasted baguette with garlic butter and herbs",
    availability: true,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 9,
    name: "Shrimp Tacos",
    category: "Main Course",
    price: "12_49",
    description: "Spicy shrimp tacos with fresh salsa and creamy sauce",
    availability: true,
    allergens: ["shellfish", "gluten"],
  },
  {
    id: 10,
    name: "Cheesecake",
    category: "Dessert",
    price: "6_99",
    description: "Creamy cheesecake with a graham cracker crust",
    availability: true,
    allergens: ["dairy", "gluten"],
  },
  {
    id: 11,
    name: "French Fries",
    category: "Side",
    price: "3_49",
    description: "Crispy golden french fries, lightly salted",
    availability: true,
    allergens: [],
  },
  {
    id: 12,
    name: "Chicken Wings",
    category: "Appetizer",
    price: "8_99",
    description: "Spicy chicken wings with ranch dipping sauce",
    availability: true,
    allergens: ["dairy"],
  },
  {
    id: 13,
    name: "Beef Tacos",
    category: "Main Course",
    price: "10_49",
    description: "Soft shell tacos with seasoned beef, cheese, and lettuce",
    availability: true,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 14,
    name: "Penne Alfredo",
    category: "Main Course",
    price: "11_99",
    description: "Penne pasta in a creamy Alfredo sauce with Parmesan",
    availability: true,
    allergens: ["gluten", "dairy"],
  },
  {
    id: 15,
    name: "Greek Salad",
    category: "Appetizer",
    price: "7_99",
    description: "Salad with cucumber, tomatoes, olives, and feta cheese",
    availability: true,
    allergens: ["dairy"],
  },
  {
    id: 16,
    name: "Fruit Bowl",
    category: "Dessert",
    price: "4_49",
    description: "Fresh seasonal fruits served in a bowl",
    availability: true,
    allergens: [],
  },
  {
    id: 17,
    name: "Clam Chowder",
    category: "Main Course",
    price: "9_99",
    description: "Creamy clam chowder with potatoes and celery",
    availability: true,
    allergens: ["shellfish", "dairy"],
  },
  {
    id: 18,
    name: "Vegan Chocolate Pudding",
    category: "Dessert",
    price: "5_49",
    description: "Rich and creamy vegan chocolate pudding",
    availability: true,
    allergens: [],
  },
  {
    id: 19,
    name: "Iced Latte",
    category: "Beverage",
    price: "4_49",
    description: "Chilled espresso with milk and ice",
    availability: true,
    allergens: ["dairy"],
  },
  {
    id: 20,
    name: "Avocado Toast",
    category: "Appetizer",
    price: "6_49",
    description: "Toasted bread with smashed avocado and a hint of lime",
    availability: true,
    allergens: ["gluten"],
  },
  {
    id: 21,
    name: "Mineral Water",
    category: "Beverage",
    price: "2_49",
    description: "Refreshing mineral water, still or sparkling",
    availability: true,
    allergens: [],
  },
  {
    id: 22,
    name: "Orange Juice",
    category: "Beverage",
    price: "3_49",
    description: "Freshly squeezed orange juice",
    availability: true,
    allergens: [],
  },
  {
    id: 23,
    name: "Green Tea",
    category: "Beverage",
    price: "2_99",
    description: "A hot cup of green tea, aromatic and soothing",
    availability: true,
    allergens: [],
  },
  {
    id: 24,
    name: "Red Wine",
    category: "Beverage",
    price: "5_99",
    description: "Fine red wine, perfect with a main course",
    availability: true,
    allergens: [],
  },
  {
    id: 25,
    name: "Beer",
    category: "Beverage",
    price: "4_49",
    description: "Chilled beer, freshly tapped",
    availability: true,
    allergens: ["gluten"],
  },
];
