export type MenuDe = {
  id: number;
  name: string;
  category: string;
  price: string;
  description: string;
  availability: boolean;
  allergens: string[];
  img: string;
};

export const menuDe: MenuDe[] = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    category: "Hauptgericht",
    price: "12_99",
    description:
      "Klassische italienische Pasta mit reichhaltiger Bolognese-Sauce",
    availability: true,
    allergens: ["gluten", "milch"],
    img: "https://images.pexels.com/photos/28575312/pexels-photo-28575312/free-photo-of-traditionelle-spaghetti-bolognese-mit-frischen-zutaten.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 2,
    name: "Caesar Salad",
    category: "Vorspeise",
    price: "6_99",
    description: "Frischer Römersalat mit Caesar-Dressing und Croutons",
    availability: true,
    allergens: ["milch", "ei"],
    img: "https://images.pexels.com/photos/257816/pexels-photo-257816.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 3,
    name: "Schokoladenkuchen",
    category: "Dessert",
    price: "5_99",
    description: "Reicher und saftiger Schokoladenkuchen",
    availability: true,
    allergens: ["gluten", "milch", "nüsse"],
    img: "https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 4,
    name: "Pizza Margherita",
    category: "Hauptgericht",
    price: "10_99",
    description: "Klassische Pizza mit Tomatensauce, Mozzarella und Basilikum",
    availability: true,
    allergens: ["gluten", "milch"],
    img: "https://images.pexels.com/photos/19602378/pexels-photo-19602378/free-photo-of-sauerteigpizza-margherita-zeit.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 5,
    name: "Gegrillter Lachs",
    category: "Hauptgericht",
    price: "14_99",
    description: "Perfekt gegrillter Lachs mit Zitronenbutter-Sauce",
    availability: true,
    allergens: ["fisch"],
    img: "https://images.pexels.com/photos/2374946/pexels-photo-2374946.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 6,
    name: "Veganer Burger",
    category: "Hauptgericht",
    price: "11_99",
    description:
      "Pflanzenbasierter Patty mit Salat, Tomate und veganer Mayonnaise",
    availability: true,
    allergens: ["gluten"],
    img: "https://images.pexels.com/photos/6546033/pexels-photo-6546033.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 7,
    name: "Mango-Smoothie",
    category: "Getränk",
    price: "4_99",
    description:
      "Erfrischender Mango-Smoothie mit frischen Mangos und Mandelmilch",
    availability: true,
    allergens: ["nüsse"],
    img: "https://images.pexels.com/photos/4955257/pexels-photo-4955257.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 8,
    name: "Knoblauchbrot",
    category: "Vorspeise",
    price: "3_99",
    description: "Geröstetes Baguette mit Knoblauchbutter und Kräutern",
    availability: true,
    allergens: ["gluten", "milch"],
    img: "https://images.pexels.com/photos/1460860/pexels-photo-1460860.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 9,
    name: "Garnelen-Tacos",
    category: "Hauptgericht",
    price: "12_49",
    description: "Würzige Garnelen-Tacos mit frischer Salsa und cremiger Sauce",
    availability: true,
    allergens: ["schalentiere", "gluten"],
    img: "https://images.pexels.com/photos/27365309/pexels-photo-27365309/free-photo-of-mexikanisches-restaurant.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 10,
    name: "Käsekuchen",
    category: "Dessert",
    price: "6_99",
    description: "Cremiger Käsekuchen mit Keksboden",
    availability: true,
    allergens: ["milch", "gluten"],
    img: "https://images.pexels.com/photos/1098592/pexels-photo-1098592.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 11,
    name: "Pommes Frites",
    category: "Beilage",
    price: "3_49",
    description: "Knusprig goldene Pommes Frites, leicht gesalzen",
    availability: true,
    allergens: [],
    img: "https://images.pexels.com/photos/1586942/pexels-photo-1586942.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 12,
    name: "Hähnchenflügel",
    category: "Vorspeise",
    price: "8_99",
    description: "Würzige Hähnchenflügel mit Ranch-Dip",
    availability: true,
    allergens: ["milch"],
    img: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 13,
    name: "Rindfleisch-Tacos",
    category: "Hauptgericht",
    price: "10_49",
    description: "Weiche Tacos mit gewürztem Rindfleisch, Käse und Salat",
    availability: true,
    allergens: ["gluten", "milch"],
    img: "https://images.pexels.com/photos/7613555/pexels-photo-7613555.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 14,
    name: "Penne Alfredo",
    category: "Hauptgericht",
    price: "11_99",
    description: "Penne mit cremiger Alfredo-Sauce und Parmesan",
    availability: true,
    allergens: ["gluten", "milch"],
    img: "https://images.pexels.com/photos/29042359/pexels-photo-29042359/free-photo-of-kostliche-pesto-penne-nudeln-in-elegantem-ambiente.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 15,
    name: "Griechischer Salat",
    category: "Vorspeise",
    price: "7_99",
    description: "Salat mit Gurken, Tomaten, Oliven und Feta-Käse",
    availability: true,
    allergens: ["milch"],
    img: "https://images.pexels.com/photos/1213710/pexels-photo-1213710.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 16,
    name: "Fruchtschale",
    category: "Dessert",
    price: "4_49",
    description: "Frische saisonale Früchte in einer Schale serviert",
    availability: true,
    allergens: [],
    img: "https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 17,
    name: "Clam Chowder",
    category: "Hauptgericht",
    price: "9_99",
    description: "Cremige Muschelsuppe mit Kartoffeln und Sellerie",
    availability: true,
    allergens: ["schalentiere", "milch"],
    img: "https://images.pexels.com/photos/16357831/pexels-photo-16357831/free-photo-of-lebensmittel-essen-mahlzeit-schussel.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 18,
    name: "Veganer Schokoladenpudding",
    category: "Dessert",
    price: "5_49",
    description: "Reicher und cremiger veganer Schokoladenpudding",
    availability: true,
    allergens: [],
    img: "https://images.pexels.com/photos/3026810/pexels-photo-3026810.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 19,
    name: "Eiskaffee",
    category: "Getränk",
    price: "4_49",
    description: "Gekühlter Espresso mit Milch und Eis",
    availability: true,
    allergens: ["milch"],
    img: "https://images.pexels.com/photos/29095101/pexels-photo-29095101/free-photo-of-eiskaffee-auf-holztisch-im-cafe-ambiente.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 20,
    name: "Avocado-Toast",
    category: "Vorspeise",
    price: "6_49",
    description: "Getoastetes Brot mit Avocado und einem Hauch Limette",
    availability: true,
    allergens: ["gluten"],
    img: "https://images.pexels.com/photos/1321942/pexels-photo-1321942.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 21,
    name: "Mineralwasser",
    category: "Getränk",
    price: "2_49",
    description: "Erfrischendes Mineralwasser, still oder sprudelnd",
    availability: true,
    allergens: [],
    img: "https://images.pexels.com/photos/593099/pexels-photo-593099.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 22,
    name: "Orangensaft",
    category: "Getränk",
    price: "3_49",
    description: "Frisch gepresster Orangensaft",
    availability: true,
    allergens: [],
    img: "https://images.pexels.com/photos/1337824/pexels-photo-1337824.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 23,
    name: "Grüner Tee",
    category: "Getränk",
    price: "2_99",
    description: "Heiße Tasse grüner Tee, aromatisch und wohltuend",
    availability: true,
    allergens: [],
    img: "https://images.pexels.com/photos/3090274/pexels-photo-3090274.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
  {
    id: 24,
    name: "Rotwein",
    category: "Getränk",
    price: "5_99",
    description: "Edler Rotwein, perfekt zum Hauptgericht",
    availability: true,
    allergens: [],
    img: "https://images.pexels.com/photos/95960/pexels-photo-95960.jpeg?auto=compress&cs=tinysrgb&w420&h=250&dpr=1",
  },
  {
    id: 25,
    name: "Bier",
    category: "Getränk",
    price: "4_49",
    description: "Kühles Bier, frisch gezapft",
    availability: true,
    allergens: ["gluten"],
    img: "https://images.pexels.com/photos/1672304/pexels-photo-1672304.jpeg?auto=compress&cs=tinysrgb&w=420&h=250&dpr=1",
  },
];
